name: sasi_cowork
description: SASI Cowork — white-label Flutter app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design System & Shared Lib
  sume_design_system:
    path: ../../packages/sume_design_system
  sasi_moni_lib:
    path: ../../packages/sasi_moni_lib

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.7.0

  # Networking
  dio: ^5.4.3+1

  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
